version: '3.8'
services:
  app:
    image: php:8.2-fpm
    container_name: codeigniter_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
